version: "3"

services:
  zookeeper:
    container_name: zookeeper-trt
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment: 
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: kafka-trt
    image: 'bitnami/kafka:latest'
    ports:
      - '9096:9096'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9096
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9096
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

# version: "3"

# services:
#   zookeeper:
#     container_name: zookeeper-trt
#     image: 'bitnami/zookeeper:latest'
#     ports:
#       - '2181:2181'
#     environment: 
#       - ALLOW_ANONYMOUS_LOGIN-yes

# kafka:
#   container_name: kafka-trt
#   image: 'bitnami/kafka:latest'
#   ports:
#     - '9096:9096'
#   environment:
#     - KAFKA_BROKER_ID=1
#     - KAFKA_CFG_LISTENERS=PLAINTEXT://:90936
#     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT:/host.docker.internal:9096
#     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#     - ALLOW_PLAINTEXT_LISTENER=yes
#   depends_on:
#     - zookeeper